#if !canImport(ObjectiveC)
import XCTest

extension HTMLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HTMLTests = [
        ("testElseBlock", testElseBlock),
        ("testElseIfBlock", testElseIfBlock),
        ("testExample", testExample),
        ("testIfBlock", testIfBlock),
        ("testWhitespaceTrimming", testWhitespaceTrimming),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HTMLTests.__allTests__HTMLTests),
    ]
}
#endif
