#if !canImport(ObjectiveC)
import XCTest

extension HTMLTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__HTMLTests = [
        ("testAllWhitespaceTrimming", testAllWhitespaceTrimming),
        ("testElseBlock", testElseBlock),
        ("testElseIfBlock", testElseIfBlock),
        ("testExample", testExample),
        ("testIfBlock", testIfBlock),
        ("testImplicitWhitespaceTrimming", testImplicitWhitespaceTrimming),
        ("testInfixWhitespaceTrimming", testInfixWhitespaceTrimming),
        ("testLeadingWhitespaceTrimming", testLeadingWhitespaceTrimming),
        ("testNoWhitespaceTrimming", testNoWhitespaceTrimming),
        ("testTrailingWhitespaceTrimming", testTrailingWhitespaceTrimming),
        ("testVisitorTextExtraction", testVisitorTextExtraction),
        ("testVisitorUppercase", testVisitorUppercase),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(HTMLTests.__allTests__HTMLTests),
    ]
}
#endif
